### ISSUE TITLE
colorpalette.xyz/ timed out :(

### ISSUE THREAD

**Issue by tomByrer** [makkoncept/colorpalette#3]
That's fine if you don't want to host it anymore, just maybe either remove the URL references from your repo or put a 'parking' page up.

Thanks for your tool!

**Comment by makkoncept** [comment]
Yeah, I'll do that. Thanks!

**Comment by makkoncept** [comment]
Hi, @tomByrer. I have updated the heroku build to reflect the latest state of the project. Also, there is now a "Deploy to Heroku" button in the Readme which you can use to deploy your own instance.
